name = "portal27-analytics"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database binding
[[d1_databases]]
binding = "DB"
database_name = "portal27-analytics"
database_id = "0bd2c0c1-665b-4b8c-8e0d-307c6c7751a7" # Se llenará después de crear la BD

# CORS headers
[vars]
ALLOWED_ORIGINS = "https://cumpleona.pages.dev"
